server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/power_forecast?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 69806980   # 改成你的MySQL密码
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Python Flask 预测服务地址
forecast:
  python-server: http://localhost:5001

# 文件上传目录
upload:
  path: D:\power_forecast_project\forecast_upload
